### ISSUE TITLE
Not working with Zway 2.2.2

### ISSUE THREAD

**Issue by stemod** [maros/Zway-InfluxDbStats#3]
Installed + Instantiated Basemodule 1.08 via "apps".
Installed InfluxDbStats 1.04 via "apps".

>  Cannot instantiate module: InfluxDbStats: TypeError: undefined is not a function

z-way-server.log:

```
[2016-04-23 17:37:50.131] [I] [core] Notification: error (core): Cannot instantiate module: InfluxDbStats: TypeError: undefined is not a function
[2016-04-23 17:37:50.167] [I] [core] TypeError: undefined is not a function
    at AutomationController.instantiateModule (automation/classes/AutomationController.js:394:24)
    at AutomationController.createInstance (automation/classes/AutomationController.js:833:23)
    at ZAutomationAPIWebRequest._.extend.createInstance (automation/ZAutomationAPIProvider.js:1027:40)
    at ZAutomationAPIWebRequest.ZAutomationWebRequest.handleRequest (automation/WebserverRequestRouter.js:258:41)
    at automation/WebserverRequestRouter.js:32:35
    at WebServer.document_root (automation/Webserver.js:29:11)
```

**Comment by sja** [comment]
You have to restart z-way-server: `service z-way-server stop && sleep 1 && service z-way-server start`

**Comment by stemod** [comment]
Thx - its working now.
